---
- name: "Configure docker repo/key in apt and install docker"
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: "Install aptitude"
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: "Install required system packages"
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: latest
        update_cache: true

    - name: "Add Docker's official GPG key to apt"
      apt_key:
        id: 7EA0A9C3F273FCD8
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: "Add Docker Repository"
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"          
        state: present
        update_cache: True
        filename: docker

    - name: "Update apt and install docker-ce"
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true
